[package]
name = "mprobe-diagnostics"
version = "0.1.0"
edition = "2021"
authors = [ "Nelu Snegur <nelu@pulsarplanet.com>" ]
keywords = [ "mongodb", "diagnostics", "ftdc", "metrics" ]
license = "MIT"
readme = "README.md"
repository = "https://github.com/nelusnegur/mprobe/crates/diagnostics"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE",
]

[dependencies]
chrono = "0.4.19"
bson = "2.2.0"
flate2 = "1.0.23"
